### PR TITLE
An idea for Group recipe to support device recipes

### PR DESCRIPTION
**Pull request by scroix**
There's an issue at the moment with the Group node recipe which utilises complex arguments in it's remote actions `{'state': 'arg'}` which isn't supported by the majority of device recipes which use a simple String enum for their argument.

This update adds a new toggle to the member parameters which is evaluated when sending a remote action, sending just the state argument, `'On'` instead of a list `{'state':'On'}`.

### CODE REVIEW

**Comment by rhulse** [comment]
I had that same issue when setting up Nodel at Te Papa, and in my case I opted for processing incoming args:

```python
arg = getStateValue(arg)
```

And here is the function:

```python
def getStateValue(arg):
  if hasattr(arg, 'get'): # does it have the '.get' function i.e. dict/map-like
    return arg['state']
  elif isinstance(arg, basestring):
    return arg
  else:
    return None
```

**Comment by scroix** [comment]
@rhulse is that signal processing from the perspective of the receiving/device node?

I'm concerned about having to update all the existing recipes to support the complex signal type being emitted from the group node.

**Comment by rhulse** [comment]
@scroix yes. At the time I could not get my head around the group code, and because this was a new setup it wasn't a hassle to do it this way.

**Comment by rhulse** [comment]
One other thought - it would be cool if the group node knew that it was connected to a device, and changed the way it sent params. That would still require all the recipes to change though, to maintain some sort of 'I am a device' state/flag.

**Comment by scroix** [comment]
@rhulse I'm a big fan! If there was a way to lookup the schema of a remote node, then neither the group node would need a `is member a device? [ ]` parameter, nor the device node in question needing a `getStateValue()` handler.

I'd be love to hear from @justparking on this

**Comment by rhulse** [comment]
@scroix I think you code is still useful - it'd just be wired up differently to interrogate its children instead of using the param.

**Comment by justparking** [comment]
Hi, @rhulse 
We've spent a long time trashing out this issue recently.

For now, can you take a look at the recipe update (121e72a2da5c61230c877945629354e4ad74d12a):

We've thought about splitting the recipe into **Control Group** and **Logical Group** but it seems like a lot of code duplication and long term management issues.

It's clear they're very similar, the only subtle difference is the way extended arguments are used.

So without splitting the node, or insisting every device support the extended argument, we thought a good compromise would be to have a flag to specifically identify members that are groups. The flag controls what remote bindings are offered.

That there are less bindings involved and with the improved labelling (group labels, local action labels, remote action labels, etc.), I'm hoping Group nodes will be easier to use and understand.

Would be nice to know your thoughts. Happy to have a chat over the phone?

I believe the changes are backwards compatible for you, but can you double-check?

**Comment by rhulse** [comment]
@justparking I'll need to spin this up and have a look. Currently getting a new exhibition out, so will be next week. Looks promising though... :-)

**Comment by scroix** [comment]
I'm also happy with the recently implemented solution. Closing pull request.

**Pull request closed without merging**
