### PR TITLE
Computer Controller *update*: add audio metering

### PR DESCRIPTION
**Pull request by scroix**
> Inspired by the recent update (d559cdb5ae3da0534f54fa42016ccdd069e24a96) which introduced support for screenshotting and CPU monitoring by @justparking.

An initial attempt at monitoring peak values in the audio stream using an additional Core Audio interface, [IAudioMeterInformation](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nn-endpointvolume-iaudiometerinformation).

###### I think I'm getting the hang of this now! 😁

It was also a good chance to streamline the use of both interfaces, and fix-up some poor memory management -- the end-points are only activated _once_ per-session.

### CODE REVIEW

**Comment by justparking** [comment]
Great addition! Keen to merge but only issue I wanted to discuss is the unit of measurement. 

Most/all DSPs and their recipes provide meter¹ readings in decibels (dB). Also, many of the related UI frontend controls do the same.

I see [GetPeakValue()](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudiometerinformation-getpeakvalue) returns a peak sample value, not in dB.

Can you update the code to use these calculations [link-to-calculations](http://www.playdotsound.com/portfolio-item/decibel-db-to-float-value-calculator-making-sense-of-linear-values-in-audio-tools).

---
¹ Gain controls are normally done in dB too. I see the Windows API offers both measurements - 
* [SetMasterVolumeScalar](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudioendpointvolume-setmastervolumelevelscalar)
* [SetMasterVolumeLevel](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudioendpointvolume-setmastervolumelevel)

Perhaps both should be offered so that gain controls can be "wired" up to them without any conversion code.

**Comment by scroix** [comment]
Thanks 😄 

It's a good point. _I think both should be available_. The PC itself provides normalised/linear controls and UI elements, so one would naturally expect they would be available **in addition to decibels.**

It's no issue to create another **action** which utilises `SetMasterVolumeLevel`. 👍 

------

However, I'm confused about the conversion from the peak value (0 - 1.0) to decibels. 

My confusion comes from the fact that the API provides a method to get the **volume** range in decibels. [[GetVolumeRange]](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudioendpointvolume-getvolumerange) which returns a result which isn't -100 dBFS to 0 dBFS like your example.

I quickly compared the two to highlight my point.

scalar-to-db

I'm not sure how to convert from a linear scalar to a _specific_ decibel range. Is there any issue with converting the normalised peak value (from the audio stream) to a different scale than the _volume_ is utilising?

**Comment by scroix** [comment]
I've gotten around to addressing your original suggestions @justparking 👏 

This latest commit includes support for decibels through an extension to the `IAudioEndpointVolume` interface. It was a *huge* pain to achieve this...! It was a massive guessing game with matching up the correct COM method slots. 😫 

But that is in the past now. Everything is fine now.

🌳 🌻 🐦 ... 🐛 

I made two design decisions I wanted to highlight with you.

#### Decision 1 - Metering
I've opted to use the calculation you suggested for **peak metering**. That we're looking at a scale of 0 to -100dBFS.

But **volume level** on the other hand, is a value from 0 to [[GetVolumeRange]](https://docs.microsoft.com/en-us/windows/win32/api/endpointvolume/nf-endpointvolume-iaudioendpointvolume-getvolumerange). In my experience this has been around -60dB.

#### Decision 2 - Swapping between metering styles
I tried providing both _decibel_ and _scalar_ **actions** and **events** but felt the node became too busy.

I also tried using a **parameter** to swap between the two metering styles. It (1) felt out of place as a parameter, and (2) involves a bit of unnecessary over-engineering to build different actions and events from parameters.

I instead opted to use an event which provides the toggling. It is minimal and useful. It works live. It makes me happy.

metering

**Comment by justparking** [comment]
You shed a lot of light on some of the Windows Audio specifics. It's been interesting to learn.

I think we might be overthinking the dB vs linear/scalar thing. Being able to dynamically select between the two is overkill I reckon. Also, I can envisage support for both at the same time could be very useful.

So what I did in a recent commit to your branch was reduce a lot of that into:
1) have the meter in dB only (very typical of DSPs)
2) have volume settable and readable in dB (very typical of DSPs)
3) also have volume settable and readable in "tapered" levels (scalar, linear, etc.) and let Windows do the hard work regarding range, increments, etc.

See screenshot below:

image

This allows flexibility in how these controls are wired-up or adjusted by one or more entities (by the end-user, other nodes, special frontends, etc.)

My recent commit to your branch covers those items and a few other little things:
1) make use of 2 decimal places for event values
2) set a pure digital silence floor threshold of -96 dB (as per [this](https://docs.microsoft.com/en-au/windows/win32/coreaudio/audio-tapered-volume-controls) MS article and also typical of DSPs)
3) (non-audio) when a screenshot cannot be performed (e.g. workstation locked), it shows a static thumbnail indicating the failure (issue #51)
4) (non-audio) I stripped out a whole lot of Win32 Interop code that wasn't referenced

Let me know how you feel about those changes.

**Comment by scroix** [comment]
Okay, firstly _I feel great_. This is ramping up to be my new favourite recipe. 👨‍🍳 

I've spun it up and my initial impressions are good. I think your compromises on the dB vs scalar question are completely sound. I appreciate all your other updates as well.

I made a very minor correctly to ensure _both_ scalar and decibel were announced to the node when the controller started-up.

**I do have one concern however.** ✋ You've removed the mapping of the meter to current system volume.

```
// map to the current system volume. otherwise we'll be ignoring the effect reducing volume has on the live metering
float v_mapped = v.Map(0f, 1.0f, 0f, Audio.VolumeScalar);

double m;
if (s_decibel)
{
    double l = Math.Log10(v_mapped) * 20; // convert to dBFS
    m = Double.IsInfinity(l) ? s_range["volMinDB"] : l; // an ultra-low result is effectively the maximum decibel value indicated by the system's "volume range"
}
else
{
    m = v_mapped * 100; // linear scalar 0 -> 1.0 to 0 -> 100
}
```

The purpose of this was to ensure that the metering was consistent with changes to system volume. _If it isn't done_, then you can end up with "loud" meters, despite having the volume imperceptibly low.

no-volume-high-metering

If I saw these meters on a dashboard absent a volume slider, I would (incorrectly) assume the sound was audible. I'm not dead-set on reintroducing the mapping, but I'd like to hear your thoughts?

**Comment by justparking** [comment]
I'm not sure it doesn't already do that? Or at least, it's doing it on the computer I'm using right now as this screen recording shows:

out

Is that different to what you see on your system? 

I noticed in the API documentation a lot of the behaviour is heavily dependent on the audio hardware /driver implementation itself.

Also, from an API point-of-view, I wonder what the difference is between the green meter and the the dark grey one.

You wrote 'if I saw these meters on a dashboard absent a volume slider, I would (incorrectly) assume the sound was audible' - But what about Mute? If you wanted to only rely on the meter, you'd need to make sure it reflected the mute state. I demonstrate that at the end of the screen recording.

So I agree with you in that with any _pre-_ gain meter, a volume and mute control are generally needed too.

Lets determine first if this Peak Meter is a _pre-_ gain meter or _post-_ meter. Let me know what you see.

**Comment by scroix** [comment]
Oh -- _fascinating_ 😕 !

My behaviour is quite different. You'll notice the meter remains untouched as I adjust the system device volume.

I tried this with two "devices", a line-out to a USB DAC, and a HDMI out to my external computer monitor (with in-built speakers).

hardware-dependant

If we can't rely on a consistent result from the API... 🤷‍♂

I think we'll have to leave it up to the implementer to ensure the users know whether the meters are _pre-gain_ or _post-meter_.

**Comment by scroix** [comment]
I must've missed this on the last pull request, but I noticed the mute action has been updated. I'll mention it here whilst we're discussing audio but it appears to be broken. 💔 

mute

I haven't had a deeper look yet.

**Pull request merged**
